version: '2.2'
services:
  elastic7:
    image: elasticsearch:7.9.2
    environment:
      - network.host=_site_
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200
  elastic8:
    image: elasticsearch:8.4.2
    environment:
      - network.host=_site_
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - action.destructive_requires_name=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200
  build:
    build:
      context: .
      dockerfile: Dockerfile.test
    working_dir: /workspace
    environment:
      - "GOFLAGS=-mod=vendor"
    volumes:
     - .:/workspace
    stdin_open: true
    tty: true


