apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-cluster-secret
  namespace: elasticsearch
type: Opaque
stringData:
  uri: http://elastic:password@elasticsearch-es-http.elasticsearch.svc:9200

