apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - name: melasticindex.kb.io
    sideEffects: None
  - name: melastictemplate.kb.io
    sideEffects: None